_target_: src.training.modeling.models.simple_vector_map_model_tt.VectorMapSimpleMLP
_convert_: 'all'


# Parameters for past trajectory
past_trajectory_sampling:
  _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
  _convert_: 'all'
  num_poses: 4      # target future poses
  time_horizon: 1.5  # [s] time horizon of future poses

# Parameters for predicted trajectory
future_trajectory_sampling:
  _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
  _convert_: 'all'
  num_poses: 16      # target future poses
  time_horizon: 8.0  # [s] time horizon of future poses
