_target_: src.training.modeling.models.tt_model.PlanningModel
_convert_: 'all'



feature_builder:
  _target_: src.training.preprocessing.feature_builders.tt_feature_builder.TTFeatureBuilder
  _convert_: "all"

